docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
site_name: zend-mvc-plugin-prg
site_description: 'Post/Redirect/Get plugin for zend-mvc controllers'
repo_url: 'https://github.com/zendframework/zend-mvc-plugin-prg'
extra:
    show_special_homepage: true
