docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
site_name: laminas-mvc-plugin-prg
site_description: 'laminas-mvc-plugin-prg: Post-Redirect-Get controller plugin for laminas-mvc'
repo_url: 'https://github.com/laminas/laminas-mvc-plugin-prg'
